export const ORDERS_ACTIONS_TYPES = {
  GET_ORDERS: 'GET_ORDERS',
  INSERT_ORDER: 'INSERT_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  SEND_ORDER: 'SEND_ORDER',
  GET_ORDERS_BY_DATE: 'GET_ORDERS_BY_DATE'
}
